### ISSUE TITLE
Add post conditions for Farmer

### ISSUE THREAD

**Issue by friedger** [pointblankdev/charisma-web#17]
Currently, recruiting farmers result in unsecure transactions.

**Comment by r0zar** [comment]
Yeah, I've been procrastinating on adding them becuase SIP13 post-conditions are still a little intimidating to me.

I'm guessing it's just all the sip9 and sip10 transfers, all together?

**Comment by r0zar** [comment]
@friedger if you do know how to implement SIP13 postconditions (for the NFT part) i could use some pointer. 

I've tried applying different combinations of will-send and not-will-send but haven't had luck yet.

```ts
if (hasLands) postConditions.push(Pc.principal(sender).willSendAsset().nft(landNftKey, uintCV(metadata.id)))
if (hasLands) postConditions.push(Pc.principal(sender).willNotSendAsset().nft(landNftKey, uintCV(String(metadata.id))))
 ```

**Comment by r0zar** [comment]
Okay! found the issue.

SIP13 tokens have a non-standard token-id (tuple) and I was still applying the standard `uint` id instead.
