### ISSUE TITLE
ByteString Error

### ISSUE THREAD

**Issue by Nemo144** [pointblankdev/charisma-web#48]
TypeError: Cannot convert argument to a ByteString because the character at index 7 has a value of 8220 which is greater than 255.
<img width="1675" alt="Screen Shot 2024-08-29 at 02 50 43" src="https://github.com/user-attachments/assets/4e056419-a6de-4eca-afb9-9c3969ba700d">

**Comment by Nemo144** [comment]
@firerum can you recreate this error on your ends and if yes find a quick fix ?

**Comment by firerum** [comment]
@Nemo144 I am unable to create the bug on my end. It works fine here.

**Comment by Nemo144** [comment]
i already pushed a fix to ross! recreated the bug on my end and fixed it
